#!/bin/sh

GUILE_VERSION=$(guile -c '(display (version))')

if [ ${GUILE_VERSION} = 1.3 ] || [ ${GUILE_VERSION} = 1.3.4 ]
then
  export LD_LIBRARY_PATH=".libs:${LD_LIBRARY_PATH}"
  export LD_LIBRARY_PATH="../g-wrap/.libs:${LD_LIBRARY_PATH}"
else
  export LTDL_LIBRARY_PATH=".:../g-wrap:${LTDL_LIBRARY_PATH}"
fi

export GUILE_LOAD_PATH=".:..:${GUILE_LOAD_PATH}"

CMD=$1

shift

exec "${CMD}" "$@"
