#!/bin/sh
exec ./guile-test-env guile -s "$0" "$@"
!#

(use-modules (g-wrap gw-gtk-spec))

(use-modules (test-gw-gtkobj))

(define test-vbox (test-gw-gtkobj-gtk-vbox-new #f 3))
(test-gw-gtkobj-gtk-container-set-reallocate-redraws test-vbox #f)

(exit 0)

;; Local Variables:
;; mode: scheme
;; End:
