;; Generated by G-Wrap, an experimental wrapper engine

(define-structure
  test-standard
  (export
    gw-test-generic/bool-bool
    gw-test-generic/double-double*
    gw-test-generic/str-null-ok
    gw-test-generic/str-int
    gw-test-generic/int
    gw-test-out+default-args
    gw-test-out-args
    gw-test-strtol
    gw-test-gw-standard-echo-const-mchars-callee-owned
    gw-test-gw-standard-echo-mchars-callee-owned
    gw-test-gw-standard-echo-const-mchars-caller-owned
    gw-test-gw-standard-echo-mchars-caller-owned
    gw-test-gw-standard-echo-ssize
    gw-test-gw-standard-echo-unsigned-long
    gw-test-gw-standard-echo-long
    gw-test-gw-standard-echo-unsigned-int
    gw-test-gw-standard-echo-int
    gw-test-gw-standard-echo-double
    gw-test-gw-standard-echo-float
    gw-test-gw-standard-get-ssize-max
    gw-test-gw-standard-get-ulong-max
    gw-test-gw-standard-get-long-max
    gw-test-gw-standard-get-ssize-min
    gw-test-gw-standard-get-long-min
    gw-test-gw-standard-get-uint-max
    gw-test-gw-standard-get-int-max
    gw-test-gw-standard-get-int-min
    gw-test-gw-standard-echo-char
    gw-test-gw-standard-echo-bool
    gw-test-gw-standard-no-op)
  (open scheme srfi-23 g-wrap.gw.standard)
  (files test-standard))
